-- Run this in the Supabase SQL editor (or as a migration) to provision the demo storage.
-- It first removes any old copy of the table so you can re-run it after manual changes.

drop table if exists public.prefs cascade;

create table if not exists public.prefs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  people smallint not null check (people between 1 and 12),
  meals text[] not null default '{}'
);

alter table public.prefs enable row level security;

create policy if not exists "Prefs allow anon access"
  on public.prefs
  for all
  using (true)
  with check (true);

comment on table public.prefs is 'Stores developer demo preference presets (people + meals list).';

insert into public.prefs (people, meals)
values (4, '{"Breakfast","Lunch","Dinner"}'::text[]);
