-- Developer quick preferences table for the preferences panel
-- Run this in the Supabase SQL editor (or as a migration) to provision the demo storage.

create table if not exists public.prefs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  people smallint not null check (people between 1 and 12),
  meals text[] not null default '{}'
);

alter table public.prefs enable row level security;

create policy if not exists "Prefs allow anon access"
  on public.prefs
  for all
  using (true)
  with check (true);

comment on table public.prefs is 'Stores developer demo preference presets (people + meals list).';
